name: this is a workflow, w-o-r-k, please

on:
    pull_request:
        branches:
            - develop
            - staging

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout a branch
              uses: actions/checkout@v2

            - name: Use node 21
              uses: actions/setup-node@v2
              with:
                  node-version: 21.x

            - name: Install dependencies
              run: npm install

            - name: Run linter
              run: npm run lint
