name: This is a workflow, w-o-r-k, please

on: 
pull_request:
  branches:
    - develop
    - staging

jobs:
test:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout a branch
        uses: actions/checkout@v1
    - name: Use Node.js 21
        uses: actions/setup-node@v1
        with: 
          node-version: 21.x
    - name: install deps
        run: npm install
    - name: Run lint
        run: npm run lint
    